post_install() {
    \rm -rf /usr/share/mate-background-properties
    \rm -rf /usr/share/backgrounds/mate

    \mkdir -p /usr/share/mate-background-properties/

    \ln -s /usr/share/backgrounds/namib/config/mate-backgrounds.xml /usr/share/mate-background-properties/mate-backgrounds.xml
    \ln -s /usr/share/backgrounds/namib /usr/share/backgrounds/mate
}

post_upgrade() {
    post_install $1
}

post_remove() {
    \rm -rf /usr/share/mate-background-properties/
    \rm -rf /usr/share/backgrounds/mate
}

